# @package _global_
job_name: pluto # 配置了一个名为pluto的训练任务
py_func: train  # 指定了训练函数为train
objective_aggregate_mode: mean  # 目标聚合模式为mean

defaults:       # 覆盖了多个默认配置，包括数据增强、数据分割、模型选择、场景过滤、自定义训练器和闪电框架配置
        - override /data_augmentation:
                  - contrastive_scenario_generator
        - override /splitter: nuplan
        - override /model: pluto_model  # 会从该路径的.yaml里加载net结构和参数
        - override /scenario_filter: training_scenarios_tiny
        - override /custom_trainer: pluto_trainer
        - override /lightning: custom_lightning
